services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - docker-network
        ports:
            - 8000:8000
